/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AwsMap {
        "apiKey": string;
        "lat": number;
        "lng": number;
        "mapName": string;
        "region": string;
        "zoom": number;
    }
}
declare global {
    interface HTMLAwsMapElement extends Components.AwsMap, HTMLStencilElement {
    }
    var HTMLAwsMapElement: {
        prototype: HTMLAwsMapElement;
        new (): HTMLAwsMapElement;
    };
    interface HTMLElementTagNameMap {
        "aws-map": HTMLAwsMapElement;
    }
}
declare namespace LocalJSX {
    interface AwsMap {
        "apiKey"?: string;
        "lat"?: number;
        "lng"?: number;
        "mapName"?: string;
        "region"?: string;
        "zoom"?: number;
    }
    interface IntrinsicElements {
        "aws-map": AwsMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aws-map": LocalJSX.AwsMap & JSXBase.HTMLAttributes<HTMLAwsMapElement>;
        }
    }
}
